version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=simpletracker.settings_local
    environment:
      - SECRET_KEY=not-so-secret
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
