# Generated by Django 3.0.3 on 2021-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('visitor_id', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
            ],
        ),
    ]
